### ISSUE TITLE
Provide Default Runtime Dependencies?

### ISSUE THREAD

**Issue by commonsguy** [doppllib/doppl-gradle#9]
Right now, if I understand correctly, all projects need:

```groovy
testCompile 'co.doppl.lib:androidbasetest:0.8.5'
testDoppl 'co.doppl.lib:androidbasetest:0.8.5.0'
```

(assuming that they have tests, which hopefully will be typical of Doppl users)

And, all projects need:

```groovy
doppl 'co.doppl.lib:androidbase:0.8.5.0'
```

(if they are not depending on anything else in the `doppl` configuration that pulls this in via transitive dependencies)

Would it make sense for the Doppl plugin to provide default dependencies for these, the way that data binding automatically adds dependencies? Developers could override those for newer versions (if the plugin falls behind, if they're working off of a snapshot, etc.), but it would save developers from having to remember to add these.

Just a thought...

**Comment by kpgalligan** [comment]
Technically, you don't need the androidbase to run doppl. If you were using gson, dagger, rxjava, and a few other libraries that have no specific "Android" in them, you wouldn't need 'androidbase'.

For testing, if you're just running standard junit, you also don't need 'androidbasetest'. The breakdown of what's in those libraries, and the docs around them, could certainly use a refresher, but the less your code is "Android-y", the less you'll need them. You could build strictly logic, more like stock j2objc, and not need them.

**Comment by commonsguy** [comment]
Ah, OK. Then this proposal isn't a good one, as there's no point in automatically adding things that aren't always needed.

Thanks for the clarification!
